services:
  - type: web
    name: car-rental
    runtime: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:WYca75xdyoPYqgs3cNuyoeeP0PQ4isrUUqqMUcB7EZE=
      - key: DB_CONNECTION
        value: postgresql
      - key: DB_HOST
        fromService:
          type: pserv
          name: car-rental-db
          property: host
      - key: DB_PORT
        fromService:
          type: pserv
          name: car-rental-db
          property: port
      - key: DB_DATABASE
        fromService:
          type: pserv
          name: car-rental-db
          property: database
      - key: DB_USERNAME
        fromService:
          type: pserv
          name: car-rental-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: pserv
          name: car-rental-db
          property: password

  - type: pserv
    name: car-rental-db
    runtime: postgresql
    ipAllowList: []  # only accessible by other services in this project